### ISSUE TITLE
Issue installing as an app on my phone

### ISSUE THREAD

**Issue by crendl** [baggachipz/tinylist#15]
The app works as expected in the browser (Safari) after linking my devices successfully.  

But adding the app to the home screen and opening it, the app opens with the default home screen, suggesting me to get started. It seems there is not link to the dedicated db instance (?).

Thanks again!

**Comment by crendl** [comment]
Found a workaround, which was manually adding my unique id!

**Comment by baggachipz** [comment]
That was going to be my suggestion. The issue is that, from the perspective of the phone, Mobile Safari in the browser is a separate memory space from "added to homescreen" PWA's. It's a difficult problem to solve, adding to homescreen and then linking up the two distinct (but seemingly similar) environments.
